### ISSUE TITLE
inversify-global.d.ts

### ISSUE THREAD

**Issue by remojansen** [retyped/inversify-tsd-ambient#1]
Hi @shyiko I just saw this package on npm and I was curious. 

The InversifyJS npm package contains a folder named `type_definitions`. That folder contains a few type definitions and one of them is `inversify-global.d.ts` which can be used for ambient declarations.

Is that file not working for you?

**Comment by shyiko** [comment]
@remojansen Thanks for asking. All the packages under https://github.com/retyped (including this one) were converted from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) is automated manner. It was made specifically to facilitate transition to [tsdm](https://github.com/shyiko/tsdm) (the goal of which is to completely remove manual chore of bringing type definitions into the project). Packages that include typings (and satisfy conditions outlines in https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages) do not require special handling and so external type definitions are not necessary (for releases with embedded typings only, though).

**Comment by remojansen** [comment]
Cool thanks for answering I understand now. Really cool project hope it goes well, `.d.ts` files is one of the few bad things about typescript.

**Comment by shyiko** [comment]
@remojansen Thanks, mate!
